name: ejercicio_01_permission_handler_camara
description: Ejercicio 01 — permission_handler, Permiso de Cámara
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
