name: ejercicio_01_configurar_firebase_y_token
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.12.1
  firebase_messaging: 16.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
